# Generated by Django 3.2.25 on 2024-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('nota_primeiro_semestre', models.FloatField()),
                ('nota_segundo_semestre', models.FloatField()),
                ('nome_professor', models.CharField(max_length=100)),
                ('numero_sala', models.CharField(max_length=10)),
            ],
        ),
    ]
