# Generated by Django 3.2.25 on 2024-09-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nota_primeiro_semestre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nota_segundo_semestre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
