# Generated by Django 3.2.25 on 2024-09-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20240904_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nota_primeiro_semestre',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nota_segundo_semestre',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
